site_name: SOP Triguna
theme:
  name: material
  features:
    - content.action.edit

markdown_extensions:
  - admonition
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

plugins:
  - search
  - roamlinks

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Triguna-Jaya-Surabaya/SOP-Triguna
repo_name: Triguna-Jaya-Surabaya/SOP-Triguna
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Warehouse:
    - SOP: Warehouse/SOP.md
    - TODO: Warehouse/TODO.md
    - Current: Warehouse/Current.md
  - Pengiriman:
    - Tidak Muat: Pengiriman/Tidak Muat.md
  - SOP:
    - Olshop: SOP/Olshop.md
  - Deliberation: Warehouse/Deliberation.md
  
